FloorWidget:
    size_hint: (0.15, 0.25)
    pos_hint: {'center_x':.62   , 'center_y':.15}
    SurfaceWidget: # gap
        bg_color: utils.rgba('#eceff1')
        shadow: False
        pos_hint: {'center_x':.9, 'center_y':.28}
        size_hint: (0.5, 0.6)
    SurfaceWidget: # gap
        bg_color: utils.rgba('#eceff1')
        shadow: False
        pos_hint: {'center_x':.04, 'center_y':.15}
        size_hint: (0.1, 0.32)